### ISSUE TITLE
[API - datastore] make episcanner data available on datastore API 

### ISSUE THREAD

**Issue by luabida** [Mosqlimate-project/Data-platform#123]

**Comment by fccoelho** [comment]
The data is updated Weekly. @esloch can let us know where the data is saved. the files are named `curves_{UF}_{disease}.csv.gz`
The database table to receive this can be named "episcanner_stats"

**Comment by esloch** [comment]
> The data is updated Weekly. @esloch can let us know where the data is saved. the files are named `curves_{UF}_{disease}.csv.gz` The database table to receive this can be named "episcanner_stats"

The files are saved in the directory: 
``` 
/opt/services/Episcanner/epi-scanner/epi_scanner/data.
```

**Comment by fccoelho** [comment]
@luabida what's the status of this issue? we need this done for the publication.

**Comment by luabida** [comment]
> @luabida what's the status of this issue? we need this done for the publication.

I checked and the episcanner tasks are running and the data is available on production, the only thing I gotta do now is the endpoint on the Platform that will access the duckdb file

**Comment by luabida** [comment]
@fccoelho just to confirm, the fields that will be availed in the endpoint will be:
```
"disease"
"CID10"
"year"
"geocode"
"muni_name"
"peak_week"
"beta"
"gamma"
"R0"
"total_cases"
"alpha"
"sum_res"
"ep_ini"
"ep_end"
"ep_dur"
```

**Comment by fccoelho** [comment]
For now yes, it should match the fields produced by episcanner downloader, but with new releases of the episcanner downloader, this schema may change.
