### ISSUE TITLE
Add an endpoint for the forecast to be consumed by Infodengue

### ISSUE THREAD

**Issue by fccoelho** [Mosqlimate-project/Data-platform#158]
This API will deliver a single table and possibly also a figure.
@luabida, please check with @eduardocorrearaujo the details. You can also open a separate issue to automate the weekly update of this forecast.

The forecasts must be done for macroregions and for state level as well.

**Comment by fccoelho** [comment]
This endpoint will require a task to run the chosen forecast model every week. The training of the model will be done offline, to avoid putting too much load on the server. @eduardocorrearaujo and I will be responsible for re-training the model and updating the file on the server.

**Comment by eduardocorrearaujo** [comment]
@luabida, I think it can be closed since the dashboard is available.

**Comment by luabida** [comment]
The same Endpoints used in the Platform serve to be consumed out of it
