### ISSUE TITLE
[Metadata] Storing Metadata

### ISSUE THREAD

**Issue by luabida** [Mosqlimate-project/Data-platform#37]
Asla has introduced the Metadata Visualization topic. I'm opening this issue to start structuring the Metadata system, and its nuances, that later will be used within Mosqlimate to generate visual elements. To do so, it will require a well organized Metadata parser and aggregator, any idea is welcome here.

### Metadata Extraction
It will be important to know the source of the metadata, the most evident information is in the django models' fields itself, they also represent controlled variables and easier to correlate (e.g. Implemented Language Model Field).

But not all metadata will be relied on models fields. To produce more flexible aggregations, some of the metadata will have to be extracted from the `Prediction.prediction` JSON field. In this case and from my point of view, here will be the "hard" part of the Metadata aggregation, since this object is open for any kind of input, _it may contain any kind of information and the same information represented in different ways_.

#### Robust Documentation & References
Providing an extensive documentation referring to the prediction's possible inputs, giving the user a guideline and a weight (?) to the sorting algorithm. This strategy will require anticipating the possible information provided by the users and instructing them to follow the best practices when outputting predictions.

#### Algorithms
I have no prior expertise with this topic

This issue is open to discussion, any insights are welcome. @fccoelho feel free to assign people to this issue.

**Comment by fccoelho** [comment]
For now I think we can only work with the data from the model table as metadata. Later we may improve this

**Comment by luabida** [comment]
While conceiving the predictions page overall structure, I've got me thinking on storing and retrieving the metadata (initially from the models' fields). There are two main issues when filtering thousands of objects from the backend: memory consumption and performance. In fact, it has been one of the discussion topics for doing API calls to retrieve all the predictions at once (#28), that resulted in a pagination limit in this case.

But pagination won't help in this case. For instance, let's imagine that the database has 100k predictions, 50k implemented in Python and the other half in R (and also that every user has passed in the correct language name as well). In the visualization, the app will display these two languages existent in the database as possible filters, grouping the implementation_language from the Predictions' Models. To reach this result through API calls, the REST server will have to paginate the entire predictions database, retrieve the implementation_language from the "model" reference in the Prediction, store the ID of this Prediction in the language set (`("python": [1,2,3,...], "r": [50001, 50002,...])`), to finally respond to the user's click to select predictions by Python or R.

Trying to surround this issue, I propose an intermediate Metadata table (or tables), that will be responsible for storing metadata tags that will be used in the API calls throughout the Prediction visualization. Every Author, Model and Prediction will be responsible for sending its information to this (or these) metadata table(s). So continuing the previous example, one of the information provided by the Metadata will be the Implementation Languages, that would return `("python", "r",)` to be used in the API call by the user:

```
curl -X 'GET' \
  'https://api.mosqlimate.org/api/registry/predictions/?implementation_language=python&limit=100&offset=0' \
  -H 'accept: application/json'
```
```
curl -X 'GET' \
  'https://api.mosqlimate.org/api/registry/predictions/?implementation_language=r&limit=100&offset=0' \
  -H 'accept: application/json'
```

---

#### Possible upcoming issues:
- When the predictions/models are deleted, what happens to the metadata reference?

#### Alternatives:
- Rely exclusively on SQL queries (from my point of view, it would become very slow when it will have to parse the Prediction's JSON field to retrieve metadata info)

@fccoelho

**Comment by fccoelho** [comment]
Hi @luabida, I don't think we need a separate metadata table.  Instead of doing the selections via SQL queries, which, I agree, would be cumbersome, we can use a search interface based on the [full text search capabilities of Postgres and Django](https://docs.djangoproject.com/en/4.2/ref/contrib/postgres/search/).  This way the user would have a simple search text box interface and the FT index will return all the model IDs matching the search. Then it is just a matter of fetching only those Ids. 

As for the amount of predictions on the database, we can adopt the practice of only returning a small subset (for example the top 10, or latest 10), to avoid large queries or pagination. Later, we can think of a way for the user to request visualization of specific predictions.

**Comment by luabida** [comment]
https://github.com/Mosqlimate-project/Data-platform/issues/38#issuecomment-1863095884
