### ISSUE TITLE
[Django predictions] Define a template to the Predictions shown in the predictions list

### ISSUE THREAD

**Issue by luabida** [Mosqlimate-project/Data-platform#42]
Predictions don't have a name, instead, they can be identified by their Model's name, Author's name, Repository, Implemented Language, Type, Predict date, and later, their metadata from the prediction itself, etc. It was once discussed in a meeting about having different colors depending on the Prediction's criteria to a better visualization. I'm opening this issue to develop the format of the predictions list in the `/predictions/` page, which information will be displayed in each row (prediction), its icons, colors, functionalities, etc. This issue is a continuation of PR #40.

### Functionalities
My intention is to create a list with hover and click events, when its clicked, a popup would be displayed with all prediction's information, including the prediction field itself. Therefore, it will require defining the information what will be displayed while its full collapsed, while its hovered and how it will be shown in the popup window.  

### Incoming data format (example):
```
{'id': 6001,
 'description': '\n'
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
                'Curabitur nisi nisi, viv\n'
                'erra nec sem a, pulvinar tempus felis. Aenean et dapibus '
                'purus. Aenean auctor acc\n'
                'umsan leo, luctus fringilla mi scelerisque eget. Donec '
                'efficitur nisl a tortor ru\n'
                'Ut vel orci eget turpis sollicitudin semper a eu dui.\n',
 'model': {'author': {'institution': 'something',
                      'user': {'name': 'Luã Bida Vacaro',
                               'username': 'luabida'}},
           'description': 'Some nice description here',
           'id': 87,
           'implementation_language': 'python',
           'name': 'Test python 86',
           'repository': 'https://github.com/Mosqlimate-project/Data-platform',
           'type': 'nowcasting'},
 'commit': '2343ab2345cd2348efghih',
 'predict_date': '2023-10-31',
 'prediction': {'test': 2343}}

```

### Fields displayed in the row
- collapsed:
  - implementation language icon
  - type
  - model name
  - author (?)
  - repository (?)
  - predict date (?)
  - date of last update (?)
- hovered:
  - id (?)
  - implementation language
  - brief description
- popup:
  - prediction json prettified
  - TBD 

### Misc
list of icons for the implemented language: https://github.com/devicons/devicon

**Comment by fccoelho** [comment]
in the colapsed mode, I would add only `predict_date`  The model name could have a link to a model details page that will open on a new page.

In the Hovered mode, Show only the description because you already have the language icon

We don't need the pop items for now. It's overkill to show JSON in the web interface, users should use the API to fetch that if they want.
