### ISSUE TITLE
[Semantic release] SR needs write permission on workflow to deploy releases 

### ISSUE THREAD

**Issue by luabida** [Mosqlimate-project/Data-platform#43]
This setting is a **blockage** for any future release. It may also require disabling the option `Require approval for first-time contributors`. Both can be found in [here](https://github.com/Mosqlimate-project/Data-platform/settings/actions). 

### NOTE
I don't have enough credentials to change it.

### DETAIL
![image](https://github.com/Mosqlimate-project/Data-platform/assets/82233055/4d09745d-48e4-406f-8bf5-6298bcdb5146)

### ERROR LOG
https://github.com/Mosqlimate-project/Data-platform/actions/runs/5714234319/job/15481156568#step:6:44

**Comment by fccoelho** [comment]
Github won't let me grant read and write permissions.

**Comment by luabida** [comment]
> Github won't let me grant read and write permissions.

me neither 🤔

**Comment by fccoelho** [comment]
@luabida These permission need to be set on each workflow yaml, using the `permissions` key
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
