### ISSUE TITLE
Implement Overview visualization as template tag

### ISSUE THREAD

**Issue by fccoelho** [Mosqlimate-project/Data-platform#74]
Create a visualization for [this Echarts plot](https://echarts.apache.org/examples/en/editor.html?c=map-bar-morph).

It should be implemented as a Django template tag with the following parameters: 

- **variable**:  to use for the bars (should support only a few pre-selected). I suggest to use total cases up to current week as default. Alternatives are
    - incidence per 100k
    - Rt ?
- **disease**

**Comment by esloch** [comment]
Done!
