### ISSUE TITLE
[API - Models] Add more parameters 

### ISSUE THREAD

**Issue by eduardocorrearaujo** [Mosqlimate-project/Data-platform#80]
By now the parameters associated with the model are shown here: https://api.mosqlimate.org/docs/registry/GET/models/#parameters_table

I think that it would be interesting to have at least two other parameters: 
* `time_scale`: weekly, daily, monthly...
* `horinzon`: how many {time_scale} values ahead are predicted 

What do you think @fccoelho?

**Comment by fccoelho** [comment]
I agree with adding one parameter called  'time_resolution" that must be a choice between the following:

- day
- week
- month
- year

The horizon is not necessary as we want to let the user chose how many time units ahead she wants to predict
the horizon could be in the prediction table....

**Comment by luabida** [comment]
Solved
