### ISSUE TITLE
Enhancement: Add content to Home Page

### ISSUE THREAD

**Issue by esloch** [Mosqlimate-project/Data-platform#87]

**Comment by luabida** [comment]
Possibly duplicated #73

**Comment by fccoelho** [comment]
Suggestion of Text.

# Mosqlimate Data API
This platform makes available data to be used in the forecast of Arbovirus diseases in Brazil. It also serves as an open registry of [forecasting models](https://api.mosqlimate.org/models/) for such diseases in Brazil. Relevant climate data is also made available to help include climate influence into the modeling.

Currently, only data for dengue and chikungunya are available through this platform. More datasets will be made available in time.  All the data made available, are in the public domain, and are official data made available by the Brazilian Ministry of Health.

The purpose of this platform is to enhance the comparability of forecasting models, by making it possible for all models to learn from the same data. The model registry is open to anyone willing to contribute, but will require creating a user account first. The Mosqlimate project reserves the right to curate the model collection and decide which one to make available through the platform.
